# Generated by Django 5.1.6 on 2025-04-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_product_additional_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sustainability_score",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="A score representing the product's sustainability",
                max_digits=4,
                verbose_name="Sustainability Score",
            ),
        ),
    ]
