# Generated by Django 5.1.6 on 2025-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="shop_logos/", verbose_name="Logo"
            ),
        ),
    ]
