# Generated by Django 5.1.6 on 2025-03-31 11:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_icon_category_is_eco_friendly_and_more"),
        ("deals", "0002_deal_eco_certifications_deal_sustainability_score"),
        ("shops", "0002_alter_shop_options_shop_carbon_neutral_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_deal_is_feat_971f29_idx",
        ),
        migrations.AddField(
            model_name="deal",
            name="carbon_footprint",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="ID in external system", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="local_production",
            field=models.BooleanField(default=False, help_text="Item produced locally"),
        ),
        migrations.AddField(
            model_name="deal",
            name="source",
            field=models.CharField(
                blank=True, help_text="Source API or scraper", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["is_featured", "is_verified"],
                name="deals_deal_is_feat_e40b9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["sustainability_score"], name="deals_deal_sustain_f1cc6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["is_verified", "start_date", "end_date"],
                name="deals_deal_is_veri_f5c3cb_idx",
            ),
        ),
    ]
