# Generated by Django 5.1.6 on 2025-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='is_eco_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sustainability_impact',
            field=models.TextField(blank=True),
        ),
    ]
