# Generated by Django 5.1.6 on 2025-03-25 23:26

import apps.shops.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_icon_category_is_eco_friendly_and_more'),
        ('locations', '0002_alter_location_city_alter_location_country_and_more'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AddField(
            model_name='shop',
            name='carbon_neutral',
            field=models.BooleanField(default=False, verbose_name='Carbon Neutral'),
        ),
        migrations.AddField(
            model_name='shop',
            name='sustainability_initiatives',
            field=models.JSONField(blank=True, default=apps.shops.models.default_list, verbose_name='Sustainability Initiatives'),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified_sustainable',
            field=models.BooleanField(default=False, verbose_name='Verified Sustainable'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='shop_banners/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(related_name='shops', to='categories.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='shop_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.JSONField(default=apps.shops.models.default_dict, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['rating'], name='shops_shop_rating_321c9c_idx'),
        ),
    ]
