# Generated by Django 5.1.6 on 2025-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_alter_shop_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shop_banners/",
                verbose_name="Banner Image",
            ),
        ),
    ]
