# Generated by Django 5.1.6 on 2025-04-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_shop_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="sustainability_score",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="A score representing the shop’s sustainability performance",
                max_digits=4,
                verbose_name="Sustainability Score",
            ),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
