# Generated by Django 5.1.6 on 2025-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScraperJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(default="WebAnalysis", max_length=100)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "sustainability_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Search Analysis Job",
                "verbose_name_plural": "Search Analysis Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
