# Generated by Django 5.1.6 on 2025-03-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_location_city_alter_location_country_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="locations_l_city_ba5543_idx",
        ),
    ]
