# Generated by Django 5.1.6 on 2025-03-31 21:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_remove_location_locations_l_city_ba5543_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="point",
        ),
        migrations.AddField(
            model_name="location",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="location",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["coordinates"], name="locations_l_coordin_1338f8_gist"
            ),
        ),
    ]
