# Generated by Django 5.1.6 on 2025-03-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='deal_images/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('redemption_link', models.URLField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='deals', to='categories.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='deals_deal_start_d_20cfdf_idx'), models.Index(fields=['is_featured'], name='deals_deal_is_feat_971f29_idx'), models.Index(fields=['discount_percentage'], name='deals_deal_discoun_ae44bc_idx'), models.Index(fields=['shop'], name='deals_deal_shop_id_6fcf1f_idx')],
            },
        ),
    ]
