# Generated by Django 5.1.6 on 2025-04-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapeddeal",
            name="job",
        ),
        migrations.DeleteModel(
            name="ScraperProxy",
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="deals_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="deals_updated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="items_scraped",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name="ScrapedDeal",
        ),
    ]
