# Generated by Django 5.1.6 on 2025-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudinaryimage",
            name="transformation_options",
            field=models.TextField(
                blank=True,
                help_text="Additional Cloudinary transformation options (JSON format)",
                null=True,
            ),
        ),
    ]
